apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground-gitlab-application
  namespace: argocd
  labels:                                   
    app: wil-playground-gitlab
  annotations:
    owner: "mpeulet"
spec:
  project: default

  source:
    repoURL: http://10.0.2.15:8929/root/test-iot.git # IP de la VM à définir
    targetRevision: HEAD
    path: dev-gitlab
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitlab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Validate=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
