# # -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.configure("2") do |config|
	
	config.vm.box = "boxomatic/alpine-3.20"
	config.vm.box_version = "20240704.0.1"
	config.vm.provider :virtualbox do |vb|
		vb.memory = 2048	
		vb.cpus = 2
	end

	config.vm.define "mpeuletS" do |server|
		server.vm.hostname = "mpeuletS"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.network "forwarded_port", guest: 80, host: 80
		server.vm.provision "shell", path: "scripts/k3s-server-install.sh"
	end
  
end
