apiVersion: v1
kind: Service
metadata:
  name: app-one
  namespace: default
  labels:
    app: svc-app1
spec:
  selector:
    app: app-one
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8080
  type: ClusterIP
  