apiVersion: v1
kind: Service
metadata:
  name: app-two
  namespace: default
  labels:
    app: svc-app2
spec:
  selector:
    app: app-two
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
  