apiVersion: v1
kind: Service
metadata:
  name: app-three
  namespace: default
  labels:
    app: svc-app3
spec:
  selector:
    app: app-three
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8080
  type: ClusterIP
  