# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVICES = {
  'server' => {
	name: 'mpeuletS',
    ip: '192.168.56.110',
  },
  'worker' => {
	name: 'mpeuletSW'
    ip: '192.168.56.111',
  }
}

Vagrant.configure("2") do |config|

	config.vm.box = "alpine/alpine64"
	config.vm.box_version = "3.7.0"
	config.vm.provision "shell", path: "scripts/provision.sh"
	config.vm.provider :virtualbox do |vb|
		vb.memory = "1024"
		vb.cpus = 1
	end

	config.vm.define server do |server|
		server.vm.hostname = SERVICES['server'][:name]
		server.vm.network "private_network", ip: SERVICES['Server'][:ip]
	end

	config.vm.define worker do |worker|
		server.vm.hostname = SERVICES['worker'][:name]
		server.vm.network "private_network", ip: SERVICES['worker'][:ip]
	end

end
  