# # -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.configure("2") do |config|
	
	config.vm.box = "debian/bookworm64"
	config.vm.box_version = "12.20250126.1"
	config.vm.provider :virtualbox do |vb|
		vb.memory = 8192	
		vb.cpus = 4
	end

	config.vm.define "mpeuletS" do |server|
		server.vm.hostname = "mpeuletS"
		server.vm.network "private_network", ip: "192.168.56.110"
		server.vm.provision "shell", path: "scripts/pre-requisite.sh"
	end
  
end
